#!/bin/zsh
# run from season sub-folder or pass parameter
# update season stats
if [[ -n $1 ]]
then
    cd $1
fi
if [[ ! -e ../season_stats.R ]]
then
    echo 'No season directory available'
    exit 1
fi
files=(batting_stats.txt batting_stats_season.txt team_batting_stats.txt team_batting_stats_season.txt)
R --slave --save < ../season_stats.R
# vim $files -S ../reformat_stats.vim -c 'argdo call ReformatStats()' -c 'xall'
