#!/bin/zsh
# run from season sub-folder or pass parameter
# update season stats
if [[ -n $1 ]]
then
    cd $1
fi
files=(batting_stats.txt batting_stats_season.txt team_batting_stats.txt team_batting_stats_season.txt)
R --save < ../season_stats.R
vim $files -S ../reformat_stats.vim
